#!/bin/sh

# Colorize commands
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto"

# Dotfiles
alias \
  e="$EDITOR" \
  f="$FILE" \
  dotfiles="/usr/bin/git --git-dir=${HOME}/.dotfiles/ --work-tree=${HOME}"
