#!/bin/sh

# Verbosity and sane defaults
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  mkdir="mkdir -p"

# Colorize commands
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto"

# Abbreviations
alias \
  e="$EDITOR" \
  f="$FILE"

# Dotfiles
alias \
  dotfiles="/usr/bin/git --git-dir=${HOME}/.dotfiles/ --work-tree=${HOME}"
