#!/bin/sh

emount() {
  local DEV="$1"
  local MOUNT_DEV="ciphered_dev"

  if [ -z $DEV ] || [ ! -e $DEV ]; then
    printf "ERROR: Bad Device Argument.\n"
    return -1
  fi

  sudo cryptsetup luksOpen $DEV $MOUNT_DEV
  [ $? -ne 0 ] && return -1

  sudo mkdir -p "/media/filipe/$MOUNT_DEV"
  sudo mount -o rw,nosuid,nodev,relatime "/dev/mapper/$MOUNT_DEV" "/media/filipe/$MOUNT_DEV"

  printf "Successfully mounted in: '/media/filipe/$MOUNT_DEV'\n"
  printf "Safely remove drive with: eumount $MOUNT_DEV\n"
  printf "Goto mounted dir with: cd /media/filipe/$MOUNT_DEV\n"
}

eumount() {
  local DEV="$1"

  if [ -z $DEV ] || [ ! -e "/media/filipe/$DEV" ]; then
    printf "ERROR: Bad Device Argument.\n"
    return -1
  fi

  sudo umount "/media/filipe/$DEV"
  sudo cryptsetup luksClose $DEV

  sudo rmdir "/media/filipe/$DEV/"
}

n () {
  # Block nesting of nnn in subshells
  if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
    echo "nnn is already running"
    return
  fi

  # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
  # To cd on quit only on ^G, remove the "export" as in:
  #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
  # NOTE: NNN_TMPFILE is fixed, should not be modified
  export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

  # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
  # stty start undef
  # stty stop undef
  # stty lwrap undef
  # stty lnext undef

  nnn "$@"

  if [ -f "$NNN_TMPFILE" ]; then
    . "$NNN_TMPFILE"
    rm -f "$NNN_TMPFILE" > /dev/null
  fi
}

to_mkv() {
  name=$1
  ffmpeg \
    -i "$name.mp4" \
    -sub_charenc ISO-8859-1 \
    -i "$name.srt" \
    -c:v copy -c:a aac -ac 2 -c:s copy -map 0:0 -map 0:1 -map 1:0 -y "$name.mkv"
}
