#========================================
#=> General
#========================================
# colors
set -g default-terminal "screen-256color"
setw -g xterm-keys on
# faster command sequences
set -s escape-time 10
# increase repeat timeout
set -sg repeat-time 600
set -s focus-events on

set -g prefix2 C-a
bind C-a send-prefix -2

set -q -g status-utf8 on
set -q -g utf8 on

set -g history-limit 5000

# edit configuration
bind e new-window -n "~/.config/tmux/tmux.conf" "sh -c '\${EDITOR:-vim} ~/.config/tmux/tmux.conf && tmux source ~/.config/tmux/tmux.conf && tmux display \"~/.config/tmux/tmux.conf sourced\"'"

# reload configuration
bind r source-file ~/.config/tmux/tmux.conf \; display '~/.config/tmux/tmux.conf sourced'

#========================================
#=> Display
#========================================
# start windows numbering at 1
set -g base-index 1
# make pane numbering consistent with windows
setw -g pane-base-index 1

# rename window to reflect current program
setw -g automatic-rename on
# renumber windows when a window is cloed
set -g renumber-windows on

# set terminal title
set -g set-titles on

# slightly longer pane indicators display time
set -g display-panes-time 800
# sligthly longer status messages display time
set -g display-time 500

# redraw status line every 15 seconds
set -g status-interval 15

set -g monitor-activity on
set -g visual-activity off

#========================================
#=> Display
#========================================
# create session
bind C-c new-session

# find session
bind C-f command-prompt -p find-session 'switch-client -t %%'

# split current window horizontally
bind - split-window -v
# split current window vertically
bind _ split-window -h

# pane navigation
bind -r h select-pane -L 
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
# swap with the next
bind > swap-pane -D
# swap with the previous
bind < swap-pane -U

# maximize current pane
#bind + run 'cut -c3- ~/.config/tmux/tmux.conf | sh -s _maximize_pane "#{session_name}" #D'

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# window navigation
unbind n
unbind p
bind -r C-h previous-window
bind -r C-l next-window
bind Tab last-window

# toggle mouse
#bind m run "cut -c3- ~/.config/tmux/tmux.conf | sh -s _toggle_mouse"

#========================================
#=> Status bar
#========================================
# status bar colors
set -g status-bg black
set -g status-fg white

# centre
set-option -g status-justify centre

# status left options
set-option -g status-left '#[fg=green][#[bg=black,fg=cyan]#S#[fg=green]]'
set-option -g status-left-length 20

# window list options
set-window-option -g window-status-format '#[fg=cyan,dim]#I#[fg=blue]:#[default]#W#[fg=grey,dim]'
set-window-option -g window-status-current-format '#[fg=green][#[fg=cyan,bold]#I#[fg=blue]:#[fg=colour230]#W#[fg=dim]#[default]#[fg=green]]'

# status right options
set -g status-right '#[fg=green][#[fg=cyan]%d %b %H:%M#[default]#[fg=green]]'
