#! /bin/sh

auto_start() {
  # Terminate all instances of sxhkd 
  killall -q sxhkd

  # Await termination
  while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done

  # Start sxhkd
  sxhkd &

  # Start bspwm in all monitors
  if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
      bspc monitor $m -d 1 2 3 4 5 6 7 8 9 10 
    done
  else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
  fi
}

config_bspwm() {
  bspc config border_width         1
  bspc config window_gap           10
  bspc config top_padding          22

  bspc config split_ratio          0.50
  bspc config borderless_monocle   true
  bspc config gapless_monocle      false

  bspc config normal_border_color  "#444444"
  bspc config active_border_color  "#444444"
  bspc config focused_border_color "#0a6cf5"
  bspc config urgent_border_color  "#ff5555"
}

add_rules() {
  bspc rule -r "*"
  bspc rule -a Thunderbird desktop='^10'
  bspc rule -a Gscreenshot state=floating
  bspc rule -a Zathura state=tiled
}

main() {
  auto_start
  config_bspwm
  add_rules
}

main
