#! /bin/sh

#========================================
#=> Autostart
#========================================
# Restart sxhkd
killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &

# Spawn bspwm in all monitors
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  [ $m = DP2 ] && xrandr --output DP2 --auto --rigth-of eDP1
  bspc monitor $m -d 1 2 3 4 5 6 7 8 9 10
done

# Launch polybar
sh $HOME/.config/polybar/launch.sh

#========================================
#=> Bspwm configuration
#========================================
bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             22

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true

bspc config normal_border_color     "#212121"
bspc config active_border_color     "#414141"
bspc config focused_border_color    "#458588"

#========================================
#=> Window rules
#========================================
bspc rule -r "*"
bspc rule -a Thunderbird desktop='focused:^10'
bspc rule -a discord desktop='focused:^5'
bspc rule -a Gscreenshot state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pavucontrol state=floating
